### ISSUE TITLE
The video's length

### ISSUE THREAD

**Issue by roibenita** [ilpoviertola/V-AURA#1]
Hi,

Is it possible to synthesize audio for a video that isn't part of the datasets you mentioned and that exceeds 2.56 seconds in length? I'm currently encountering the following error:

RuntimeError: The size of tensor a (24) must match the size of tensor b (32) at non-singleton dimension.

Thanks,
Roi

**Comment by Apple-jun** [comment]
May I ask if you have solved this problem?

**Comment by ilpoviertola** [comment]
@Apple-jun, you can generate arbitrarily long audio for a video. The video must havea  sample rate of 25fps. Check [demo.ipynb](https://github.com/ilpoviertola/V-AURA/blob/main/demo.ipynb).
