### ISSUE TITLE
About Imagebind Score

### ISSUE THREAD

**Issue by Ceaglex** [ilpoviertola/V-AURA#2]
Hi! I wonder how you calculate the ImageBind Score of a video? Do you get some frames of the video and calculate the imagebind score of the picture then average them? How you select the frames?
By the way, I wonder if it is convenient for you to share the ImageBind score of each video? It will be helpful !
Thank you in advance!

**Comment by ilpoviertola** [comment]
Hello!

Checkout the official repo of [ImageBind](https://github.com/facebookresearch/ImageBind). There is instructions how to extract embeddings for video and audio data. Then the score is calculated as a cosine similarity between the visual and auditory streams within each video. 

You can find the precomputed scores [here](https://github.com/ilpoviertola/V-AURA/tree/main/data/excluded_files/filtered_examples_vggsound).

**Comment by Ceaglex** [comment]
Thank a lot!
